[package]
name = "zapier-automation-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/core/lib.rs"

[dependencies]
candid = "0.10.14"
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
ic-cdk-timers = "0.6.0"
serde = { version = "1.0", features = ["derive"] }